apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-09-03T08:24:35Z"
  labels:
    app: nifi
    run: test
  name: nifi-standalone
  uid: 43583c64-ce24-11e9-9cda-42010a80027f
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32579
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nifi
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
