apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nifi
  name: nifi-standalone
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nifi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nifi
    spec:
      containers:
      - image: us.gcr.io/soju-mobile-lle/aidi/nifi/standalone:1.7.1
        imagePullPolicy: IfNotPresent
        name: nifi
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
