apiVersion: v1
kind: Service
metadata:
  labels:
    app: nifi
  name: nifi-ui
spec:
  externalTrafficPolicy: Cluster
  loadBalancerSourceRanges:
  - 14.143.67.182/32
  - 182.74.184.26/32
  - 66.232.234.48/32
  - 66.232.236.211/32
  - 66.232.234.50/32
  ports:
  - name: ui
    nodePort: 31319
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nifi
  sessionAffinity: None
  type: NodePort
status:


